### ISSUE TITLE
can't compile atinout on immortalwrt 21.02

### ISSUE THREAD

**Issue by Nurwahyu99** [4IceG/luci-app-atinout-mod#10]
make[1] package/download
 make[2] -C package/atinout download
    ERROR: package/atinout failed to build.
make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
 make[1] target/download
 make[2] -C target/linux download

**Comment by 4IceG** [comment]
I don't know immortalwrt 21.02, I don't know what they changed there. I compiled packages from clean OpenWrt sources for versions 21.02/22.03 and had no problems/errors.

Add my sources to your Openwrt, you can do this in two ways:

```
cd feeds/luci/applications/
git clone https://github.com/4IceG/luci-app-atinout-mod.git
cd ../../..
./scripts feeds update -a; ./scripts/feeds install -a
make menuconfig
```

or e.g.

```
cd packages/
git clone https://github.com/4IceG/luci-app-atinout-mod.git
git pull
make package/symlinks
make menuconfig
```

You may need to correct the file paths and the number of folders to look like this:
```
feeds/luci/applications/luci-app-atinout-mod/Makefile
feeds/luci/applications/atinout/Makefile
```
or
```
packages/luci-app-atinout-mod/Makefile
packages/atinout/Makefile
```

and compiling the package:
`make V=s -j1 package/luci-app-atinout-mod/compile`
or e.g.
`make V=s -j1 feeds/luci/applications/luci-app-atinout-mod/compile`

**Comment by Nurwahyu99** [comment]
how about atinout package?

**Comment by 4IceG** [comment]
The package should normally be downloaded from github, which is why I wrote
above what the path to it should look like. The atinout package is in the
luci-app-atinout-mod dependencies, so it should compile together with the
package.

pon., 4 kwi 2022, 00:15 użytkownik Nurwahyu99 ***@***.***>
napisał:

**Comment by Nurwahyu99** [comment]
thank you.  I have found the fix. add a custom repo in my openwrt 

src/gz custom_generic https://raw.githubusercontent.com/lrdrdn/my-opkg-repo/main/generic
src/gz custom_arch https://raw.githubusercontent.com/lrdrdn/my-opkg-repo/main/aarch64_cortex-a53
