### ISSUE TITLE
AT command to know own phone number

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-atinout-mod#12]
Shall we add one?

I found this one:
**AT+CNUM**
https://stackoverflow.com/questions/25969855/at-command-to-know-own-phone-number

**Comment by 4IceG** [comment]
Hi @bam80 , there is no point in adding this command because it is not universal, I tested it on 2 different modems and it did not work.

**Comment by bam80** [comment]
It probably depends on mobile operator also.
It works here, maybe having a command which works at least potentially is already has a point.
