### ISSUE TITLE
Extend AT Reply windows

### ISSUE THREAD

**Issue by stich86** [4IceG/luci-app-atinout-mod#14]
hi mate,

can you extend AT reply windows increasing width from 77% to 420%?

This is on line 34 on file atcommand.htm

Tested on my build and seem the correct size to see all information

Let me know :)

**Comment by 4IceG** [comment]
Hi Dude :) , it's not better to remove the width parameter completely? you have seen that one theme uses it and the other does not. By setting such a large value, we can disrupt other themes.
