### ISSUE TITLE
broken link in Readme

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-atinout-mod#15]
The link is broken:
https://github.com/4IceG/luci-app-atinout-mod/blob/814a995df8cc01e6fdefa2456040ae161961c605/README.md?plain=1#L4

It seems upstream has adopted these sources already:
https://github.com/koshev-msk/modemfeed/commit/89c04024fbecac9c48f56962d2be3baa2dbaf5ea

**Comment by 4IceG** [comment]
The link is not valid because the package is old and not updated.

**Comment by bam80** [comment]
So it's not fixed yet, could you reopen then?
