### ISSUE TITLE
populate /etc/atcommands.user with more commands

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-atinout-mod#17]
I see on the screenshot the file is populated with a lot of useful commands.
Forcing the user to fill all that by hand is probably not very kind.

Could we ship these commands in the app distribution?
I know they might be modem-specific, but still it's easier to remove excessive than add non-existent ones, IMO.

**Comment by 4IceG** [comment]
I have not added a list of commands so that inexperienced users do not damage the modem by accidentally clicking it.

I can add my list of commands on github, but I don't know if it makes sense. I only use one modem manufacturer.

**Comment by bam80** [comment]
We could add sane commands in this list, as `ATI` and such.
> I can add my list of commands on github

Anyway, could you add your list in text format somewhere, please?
That could be e.g. `/etc/atcommands.user.sample` included in the package, so users could adopt it easily.

**Comment by 4IceG** [comment]
Hi @bam80 ,
I added an example/my list of at commands to the readme for the package https://github.com/4IceG/luci-app-atcommands. I haven't used atinout for a long time, so I haven't updated readme or the package.

I don't want to add sample files to package because then I read comments on the Internet so that users don't stupidly click on the commands from the list.

**Comment by bam80** [comment]
Thanks, but how about including the `/etc/atcommands.user.sample` file to the package?
That way users are responsible if they renaming it to the actual one, and it's still easier to adopt.

**Comment by 4IceG** [comment]
It's safe for me not to add anything.

I assume that users are reasonable and will consider adding useful commands to their list.

**Comment by bam80** [comment]
I had hard times to acquire that list, and even now when you published it it's hidden quite a lot.
I wouldn't arise the issue if it was not problematic on practice.
