### ISSUE TITLE
JS port?

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-atinout-mod#18]
Are you planning to port it to JS?

**Comment by 4IceG** [comment]
As far as I know, Konstantine rewrote package to JS ([luci-app-atinout](https://github.com/koshev-msk/modemfeed/tree/master/luci/applications/luci-app-atinout)) using my code from luci-app-atcommands.

**Comment by bam80** [comment]
Hmm, should we make this package deprecated then?
I can make a note in the Readme if you want.
