### ISSUE TITLE
Can it compile for mips_24kc?

### ISSUE THREAD

**Issue by Kningo** [4IceG/luci-app-atinout-mod#2]
Can it compile for mips_24kc? I'm using a router with this architecture, but I can't make it myself.

**Comment by 4IceG** [comment]
Hi Kningo, write what router you have and I will try to compile the package.

**Comment by Kningo** [comment]
GL.iNet GL-AR300M (128NAND)
![image](https://user-images.githubusercontent.com/44658789/103398044-d747dd00-4b75-11eb-959e-76fe5fa076a9.png)

**Comment by 4IceG** [comment]
Hi Kningo, I have compiled the packages for the latest snapshot.
[AllMy.zip](https://github.com/4IceG/luci-app-atinout-mod/files/5756840/AllMy.zip)

**Comment by Kningo** [comment]
Thanks bro, it worked out well.
![Screenshot_2021-01-01-07-18-46-931_com android chrome](https://user-images.githubusercontent.com/44658789/103430712-ce9ce880-4c01-11eb-8219-4ad59a35b4c0.jpg)
