### ISSUE TITLE
Permission denied when sending any AT command

### ISSUE THREAD

**Issue by Harwesta** [4IceG/luci-app-atinout-mod#3]
Hi

An error occurs when sending any AT command: "Permission denied"
Xiaomi Mi mini (Mediatek MT7620)
OpenWrt stable 19.07.7 r11306-c4a6851c72 (git-21.044.30835-34e0d65) 
![atinout](https://user-images.githubusercontent.com/65107625/112257618-fc388180-8c86-11eb-8e8e-ea6e55363bc1.jpg)

**Comment by 4IceG** [comment]
Hi,
Find the file on the router (/ usr / bin / luci-app-atinout) and check if it is executable or execute the command in console
chmod 755 /usr/bin/luci-app-atinout.

**Comment by Harwesta** [comment]
In truth... for some reason this file isn't executable.

before:
```
root@MiMini:~# ls -l /usr/bin/luci-app-atinout
-rw-rw-r--    1 root     root           144 Feb 15 20:22 /usr/bin/luci-app-atinout
```

after:
```
root@MiMini:~# chmod 755 /usr/bin/luci-app-atinout
root@MiMini:~# ls -l /usr/bin/luci-app-atinout
-rwxr-xr-x    1 root     root           144 Feb 15 20:22 /usr/bin/luci-app-atinout
```

And works fine.
Please describe this feature in readme file.
