### ISSUE TITLE
Compile for mediatek?

### ISSUE THREAD

**Issue by segaofice** [4IceG/luci-app-atinout-mod#4]
I'm not sure how to go about compliling this for a mediatek mt7621. I am on a zbt-wg3526 router.

**Comment by 4IceG** [comment]
Hi segaofice but what do you ask? you have a problem with your own compilation or do you want me to build packages for your router?

**Comment by 4IceG** [comment]
Own compilation in short is:
1.Download the archive and extract atinout and luci-app-atinout-mod to the packages folder
2. make package / symlinks
3. make menuconfig then Luci> Applications and select luci-app-atinout-mod
4. make packages / luci-app-atinout-mod / compile or make V = s -j1

**Comment by segaofice** [comment]
If you could I would appreciate the help, I'm not very savy with make.

**Comment by 4IceG** [comment]
Ok, I'll make package / s for version 19.07.7 with free time after work.

**Comment by 4IceG** [comment]
[IPK.zip](https://github.com/4IceG/luci-app-atinout-mod/files/6222722/IPK.zip)

**Comment by segaofice** [comment]
Working great, thank you for all your hard work.
