### ISSUE TITLE
Pi4 Malformed package

### ISSUE THREAD

**Issue by DerAlSem** [4IceG/luci-app-atinout-mod#5]
May i kindly ask you to compily for Raspberry Pi4?

pkg_init_from_file: Malformed package file atinout_0.9.1_arm_cortex-a9_vfpv3-d16.ipk

**Comment by 4IceG** [comment]
Hi @DerAlSem , write which version of Openwrt you are using exactly, then when I have a moment I will compile but I do not promise anything 100%.
