### ISSUE TITLE
Permission denied at opkg install

### ISSUE THREAD

**Issue by erdoukki** [4IceG/luci-app-atinout-mod#6]
```
Configuring luci-app-atinout-mod.
//usr/lib/opkg/info/luci-app-atinout-mod.postinst: /usr/lib/opkg/info/luci-app-atinout-mod.postinst-pkg: line 4: /sbin/set_at_port.sh: Permission denied
```

**Comment by erdoukki** [comment]
the scripts need executable flags...
May be the Makefile is missing a install section with INSTALLBIN...

**Comment by 4IceG** [comment]
Thank you for reporting. I know the error is occuring but I haven't found an effective way to fix it.

**Comment by erdoukki** [comment]
fixed by setting the permissions **before** building the package (may be a bug in luci packaging ?)
