### ISSUE TITLE
atinout unresolved. Can we use socat?

### ISSUE THREAD

**Issue by beinginorbit** [4IceG/luci-app-atinout-mod#8]
I don’t think atinout is available for my hardware without compilation (GLiNet B1300). Could you assist in compiling or possibly use socat instead?

```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency atinout for luci-app-atinout-mod
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-atinout-mod found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-atinout-mod. 
```

**Comment by 4IceG** [comment]
Hi, you can easily check if the program swap will work, upload files from
gui manually then just change two files. I can test it only tomorrow at my
free time.

sob., 9 paź 2021, 11:54 użytkownik Chris LeBlanc ***@***.***>
napisał:

**Comment by 4IceG** [comment]
Try
https://github.com/4IceG/luci-app-socat/releases/download/1.0-09102021/luci-app-socat_1.0-09102021_all.ipk

**Comment by beinginorbit** [comment]
Thanks for this, I tried the socat app and posted an install issue. That said, is it difficult to build atinout? Does it have to be built on the same hardware as it needs to run on? I can try that route too so you don't have to maintain two packages.

**Comment by 4IceG** [comment]
The compilation itself is not difficult, it only requires a lot of time
depending on the power of the computer.

niedz., 10 paź 2021, 05:21 użytkownik Chris LeBlanc <
***@***.***> napisał:
