### ISSUE TITLE
Can't install on OpenWrt 21.02.2

### ISSUE THREAD

**Issue by Nurwahyu99** [4IceG/luci-app-atinout-mod#9]
Can't install atinout and luci-app-atinout on OpenWrt 21.02.2

**Comment by 4IceG** [comment]
Hi, but what error is this, is there any message?

pt., 1 kwi 2022, 14:32 użytkownik Nurwahyu99 ***@***.***>
napisał:

**Comment by Nurwahyu99** [comment]
root@ImmortalWrt:~# opkg install luci-app-atinout-mod_1.3.2-20220315_all.ipk 
Unknown package 'luci-app-atinout-mod'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency atinout for luci-app-atinout-mod
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-atinout-mod found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-atinout-mod. 

i install on openwrt immortalwrt 21.02 snapshot kernel 5.4.188

**Comment by 4IceG** [comment]
Hi,
My package is not available in the OpenWrt repository and you have to install it manually as below:
```
wget https://github.com/4IceG/luci-app-atinout-mod/releases/download/1.3.2-20220315/luci-app-atinout-mod_1.3.2-20220315_all.ipk -O /tmp/luci-app-atinout-mod_1.3.2-20220315_all.ipk
opkg install /tmp/luci-app-atinout-mod_1.3.2-20220315_all.ipk
```
I guess the atinout package is also not in the OpenWrt repository (unless someone added it to immortalwrt 21.02, but I do not know) and you have to compile it yourself.

**Comment by Nurwahyu99** [comment]
when compiling there is an error too
